# Generated by Django 3.0.8 on 2020-07-14 20:39

from django.db import migrations
from django.utils.text import slugify


def populate_slug(apps, schema_editor):
    Module = apps.get_model('modules', 'Module')
    for module in Module.objects.all():
        module.slug = slugify(module.title)
        module.save()


class Migration(migrations.Migration):
    dependencies = [
        ('modules', '0002_module_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slug)
    ]
