# Generated by Django 3.0.8 on 2020-07-14 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_populating_slug'),
    ]

    operations = [
    ]
