# Generated by Django 3.0.8 on 2020-07-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_classs'),
    ]

    operations = [
        migrations.AddField(
            model_name='classs',
            name='vimeo_id',
            field=models.CharField(default='1', max_length=32),
        ),
    ]
