# Generated by Django 3.0.8 on 2020-07-27 14:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0002_subscription_creation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['team', 'date']},
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'team')},
        ),
    ]
